### ISSUE TITLE
Periodic URL check file is missing

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#776]
I just had the periodic URL checker run on one of my C-MOOR repos for the first time (love it! great for repos that aren't being actively updated).

When I try to click on the link in the issue to see the list of problematic URLs, it gives me a 404 error. Here's the issue it filed: https://github.com/C-MOOR/C-MOOR_Template/issues/33

**Comment by cansavvy** [comment]
I did address this issue, we just need to send out a sync for it.

**Comment by cansavvy** [comment]
@KatherineCox sent out a sync that should fix this but take a careful look at it to see if it is what you want! Thanks for letting us know about the problem!

**Comment by KatherineCox** [comment]
@cansavvy Thanks for working on this!
 
Unfortunately I can't get sync updates because of #773 . Which files do I need to manually update to get this working?

Is it just `.github/workflows/check-url.yml` ?

**Comment by cansavvy** [comment]
Oh I thought we resolved it so you would get updates now. We can look into that but yes in the meantime that is the file you need to copy over.

**Comment by KatherineCox** [comment]
No, sync is still failing with `remote: Permission to C-MOOR/C-MOOR_Template.git denied to cansavvy`

https://github.com/jhudsl/OTTR_Template/actions/runs/12715527505

**Comment by KatherineCox** [comment]
> yes in the meantime that is the file you need to copy over.

Thanks!

**Comment by KatherineCox** [comment]
Looks like the URL check is working for me now, after manually updating `.github/workflows/check-url.yml` 🎉 

I think you can close this issue, since the URL checker is fixed. It's just #773 that's a problem for me now.
